
package jframe;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Computer Gallery
 */
public class Home_page extends javax.swing.JFrame {

    /**
     * Creates new form Home_page
     */
    public Home_page() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMemberButton = new javax.swing.JButton();
        newBook_button = new javax.swing.JButton();
        IssueBook_button = new javax.swing.JButton();
        returnBook_button = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        show_student_book_list = new javax.swing.JButton();
        update_delete_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newMemberButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/member-add-on-300x300.png"))); // NOI18N
        newMemberButton.setText("New Member");
        newMemberButton.setPreferredSize(new java.awt.Dimension(159, 56));
        newMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMemberButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newMemberButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        newBook_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/New book.png"))); // NOI18N
        newBook_button.setText("New Books");
        newBook_button.setPreferredSize(new java.awt.Dimension(159, 56));
        newBook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBook_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(newBook_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        IssueBook_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/issue book.png"))); // NOI18N
        IssueBook_button.setText("Issue Book");
        IssueBook_button.setPreferredSize(new java.awt.Dimension(159, 56));
        IssueBook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBook_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(IssueBook_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        returnBook_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/return book png.png"))); // NOI18N
        returnBook_button.setText("Return Book");
        returnBook_button.setMaximumSize(new java.awt.Dimension(159, 26));
        returnBook_button.setMinimumSize(new java.awt.Dimension(159, 26));
        returnBook_button.setPreferredSize(new java.awt.Dimension(159, 56));
        returnBook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBook_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(returnBook_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, -1, -1));

        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/exit.png"))); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.setMaximumSize(new java.awt.Dimension(159, 56));
        logout_btn.setMinimumSize(new java.awt.Dimension(159, 56));
        logout_btn.setPreferredSize(new java.awt.Dimension(159, 56));
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });
        getContentPane().add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Statics.png"))); // NOI18N
        jButton7.setText("Statistics");
        jButton7.setPreferredSize(new java.awt.Dimension(159, 56));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        show_student_book_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/New book.png"))); // NOI18N
        show_student_book_list.setText("Student & Book List");
        show_student_book_list.setPreferredSize(new java.awt.Dimension(159, 22));
        show_student_book_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_student_book_listActionPerformed(evt);
            }
        });
        getContentPane().add(show_student_book_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 240, 50));

        update_delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/New book.png"))); // NOI18N
        update_delete_button.setText("Update & Delete");
        update_delete_button.setPreferredSize(new java.awt.Dimension(159, 22));
        update_delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_delete_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(update_delete_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/Library_Book_532388_1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1382, 776);
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout?","Select",JOptionPane.YES_NO_OPTION);
        if (a==0) {
            setVisible(false);
            new Login_page().setVisible(true);
        }
    }//GEN-LAST:event_logout_btnMouseClicked

    private void newMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMemberButtonActionPerformed
        // TODO add your handling code here:
        new newMember().setVisible(true);
    }//GEN-LAST:event_newMemberButtonActionPerformed

    private void newBook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBook_buttonActionPerformed
        // TODO add your handling code here:
        new New_book().setVisible(true);
    }//GEN-LAST:event_newBook_buttonActionPerformed

    private void IssueBook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBook_buttonActionPerformed
        // TODO add your handling code here:
        new Issue_book().setVisible(true);
    }//GEN-LAST:event_IssueBook_buttonActionPerformed

    private void returnBook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBook_buttonActionPerformed
        // TODO add your handling code here:
        new Return_book().setVisible(true);
    }//GEN-LAST:event_returnBook_buttonActionPerformed

    private void update_delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_delete_buttonActionPerformed
        // TODO add your handling code here:
        new Update_delete_book().setVisible(true);
    }//GEN-LAST:event_update_delete_buttonActionPerformed

    private void show_student_book_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_student_book_listActionPerformed
        // TODO add your handling code here:
        new Student_Book_List().setVisible(true);
    }//GEN-LAST:event_show_student_book_listActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Statistics().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IssueBook_button;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton newBook_button;
    private javax.swing.JButton newMemberButton;
    private javax.swing.JButton returnBook_button;
    private javax.swing.JButton show_student_book_list;
    private javax.swing.JButton update_delete_button;
    // End of variables declaration//GEN-END:variables
}
