
package jframe;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import lms.ConnectionProvider;


public class New_book extends javax.swing.JFrame {

    /**
     * Creates new form New_book
     */
    public New_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bookId_editText = new javax.swing.JTextField();
        bookName_editText = new javax.swing.JTextField();
        publiser_editText = new javax.swing.JTextField();
        publishYear_editText = new javax.swing.JTextField();
        price_editText = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Book ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 125, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Book name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 165, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Publisher:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 205, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Publish year:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 245, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Quantity:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 285, -1, -1));

        bookId_editText.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(bookId_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 125, 255, -1));

        bookName_editText.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(bookName_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 165, 255, -1));

        publiser_editText.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(publiser_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 205, 255, -1));

        publishYear_editText.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(publishYear_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 245, 255, -1));

        price_editText.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(price_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 285, 255, -1));

        save_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/save-icon--1.png"))); // NOI18N
        save_button.setText("save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 339, -1, -1));

        close_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/red-x-mark-transparent-background-3.png"))); // NOI18N
        close_button.setText("close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 339, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/123456.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(700, 450));
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_close_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
        
        String bookId = bookId_editText.getText();
        String book_name = bookName_editText.getText();
        String publisher_name = publiser_editText.getText();
        String publish_year = publishYear_editText.getText();
        String quantity = price_editText.getText();
        
        try{
            Connection con = ConnectionProvider.getCon();
            
            Statement st = con.createStatement();
            String query1 = "INSERT INTO book_details VALUES('"+bookId+"', '"+book_name+"', '"+publisher_name+"', '"+publish_year+"', '"+quantity+"')";
            st.executeUpdate(query1);
            JOptionPane.showMessageDialog(null, "Successfully updated");
            setVisible(false);
            new New_book().setVisible(true);
        }
        catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null, "Book id is already exist");
            setVisible(false);
            new New_book().setVisible(true); 
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new New_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookId_editText;
    private javax.swing.JTextField bookName_editText;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField price_editText;
    private javax.swing.JTextField publiser_editText;
    private javax.swing.JTextField publishYear_editText;
    private javax.swing.JButton save_button;
    // End of variables declaration//GEN-END:variables
}
