
package jframe;

import java.sql.*;
import javax.swing.JOptionPane;
import lms.ConnectionProvider;

/**
 *
 * @author Computer Gallery
 */
public class newMember extends javax.swing.JFrame {

    /**
     * Creates new form newMember
     */
    public newMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_editText = new javax.swing.JTextField();
        name_editText = new javax.swing.JTextField();
        fatherName_editText = new javax.swing.JTextField();
        faculty_comboBox = new javax.swing.JComboBox<>();
        dept_comboBox = new javax.swing.JComboBox<>();
        save_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Student ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Father's Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Faculty Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Department Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        id_editText.setBackground(new java.awt.Color(255, 255, 204));
        id_editText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(id_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 280, -1));

        name_editText.setBackground(new java.awt.Color(255, 255, 204));
        name_editText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(name_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 280, -1));

        fatherName_editText.setBackground(new java.awt.Color(255, 255, 204));
        fatherName_editText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(fatherName_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 280, -1));

        faculty_comboBox.setBackground(new java.awt.Color(255, 255, 204));
        faculty_comboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        faculty_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty of Arts", "Faculty of Business Administration", "Faculty of Engineering and Technology", "Faculty of Law" }));
        getContentPane().add(faculty_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 280, -1));

        dept_comboBox.setBackground(new java.awt.Color(255, 255, 204));
        dept_comboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dept_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department of English", "Department of Business Admistration", "Department of CSE", "Department of EEE", "Department of Law" }));
        getContentPane().add(dept_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 280, -1));

        save_btn.setBackground(new java.awt.Color(255, 204, 204));
        save_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/save-icon--1.png"))); // NOI18N
        save_btn.setText("save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        close_btn.setBackground(new java.awt.Color(255, 204, 204));
        close_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/red-x-mark-transparent-background-3.png"))); // NOI18N
        close_btn.setText("close");
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/123456.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        setSize(new java.awt.Dimension(700, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        String studentId = id_editText.getText();
        String name = name_editText.getText();
        String father_name = fatherName_editText.getText();
        String faculty_name  = (String) faculty_comboBox.getSelectedItem();
        String dept_name  = (String) dept_comboBox.getSelectedItem();
        
        try{
            Connection con = ConnectionProvider.getCon();
            
            Statement st = con.createStatement();
            String insertQuery = "INSERT INTO student VALUES('"+studentId+"','"+name+"', '"+father_name+"', '"+faculty_name+"', '"+dept_name+"')";
            st.executeUpdate(insertQuery);
            JOptionPane.showMessageDialog(null, "Succussfully updated");
            setVisible(false);
            new newMember().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Student id already exist");
            setVisible(false);
            new newMember().setVisible(true);
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_close_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JComboBox<String> dept_comboBox;
    private javax.swing.JComboBox<String> faculty_comboBox;
    private javax.swing.JTextField fatherName_editText;
    private javax.swing.JTextField id_editText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name_editText;
    private javax.swing.JButton save_btn;
    // End of variables declaration//GEN-END:variables
}
