/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import lms.ConnectionProvider;

/**
 *
 * @author Computer Gallery
 */
public class Return_book extends javax.swing.JFrame {

    /**
     * Creates new form Return_book
     */
    public Return_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookId_editText = new javax.swing.JTextField();
        studentId_editText = new javax.swing.JTextField();
        issueDate_editText = new javax.swing.JTextField();
        dueDate_editText = new javax.swing.JTextField();
        return_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(325, 125));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Book ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 121, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 165, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Issue date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 209, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Due date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 253, -1, -1));

        bookId_editText.setBackground(new java.awt.Color(255, 255, 204));
        bookId_editText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(bookId_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 118, 248, -1));

        studentId_editText.setBackground(new java.awt.Color(255, 255, 204));
        studentId_editText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(studentId_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 162, 248, -1));

        issueDate_editText.setBackground(new java.awt.Color(255, 255, 204));
        issueDate_editText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(issueDate_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 206, 248, -1));

        dueDate_editText.setBackground(new java.awt.Color(255, 255, 204));
        dueDate_editText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(dueDate_editText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 248, -1));

        return_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        return_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/return book png.png"))); // NOI18N
        return_button.setText("Return");
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(return_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        close_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/red-x-mark-transparent-background-3.png"))); // NOI18N
        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        search_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/search.png"))); // NOI18N
        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/123456.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(700, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        String book_id = bookId_editText.getText();
        String student_id = studentId_editText.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = " SELECT * FROM `issue` WHERE book_id = '"+book_id+"' and student_id = '"+student_id+"' and return_book = 'Pending' ";
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next()){
                issueDate_editText.setText(rs.getString(3));
                dueDate_editText.setText(rs.getString(4));
                bookId_editText.setEditable(false);
                studentId_editText.setEditable(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect book id or student id");
                setVisible(false);
                new Return_book().setVisible(false);
            }
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_buttonActionPerformed
        // TODO add your handling code here:
        String book_id = bookId_editText.getText();
        String student_id = studentId_editText.getText();
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            String query = " UPDATE issue SET return_book = 'Returned' WHERE student_id = '"+student_id+"' AND book_id = '"+book_id+"' ";
            st.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null, "Book successfully returned");
            
            updateBookCount();
            
            setVisible(false);
            new Return_book().setVisible(true);
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_return_buttonActionPerformed

    public void updateBookCount(){
       String book_id = bookId_editText.getText();
       try{
           Connection con = ConnectionProvider.getCon();
           Statement st = con.createStatement();
           String query = " UPDATE book_details SET quantity = quantity + 1 WHERE book_id = '"+book_id+"' ";
           int rowCount = st.executeUpdate(query);
           if(rowCount > 0){
               JOptionPane.showMessageDialog(null, "Book count Succussfully updated");
           }
           
       }
       catch(HeadlessException | SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }
    
    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_close_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookId_editText;
    private javax.swing.JButton close_button;
    private javax.swing.JTextField dueDate_editText;
    private javax.swing.JTextField issueDate_editText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton return_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField studentId_editText;
    // End of variables declaration//GEN-END:variables
}
